### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by niktek** [ghostdevv/extractinator#17]
Hi,

Just wanted to test this out on the Skeleton codebase and got the following:

```
~/code/skeleton/packages/skeleton pnpm extractinator extract src/lib out/
{
  dts_path: '/Users/nik/code/skeleton/packages/skeleton/.extractinator/dts-1703126806803/additional-svelte-typings.d.d.ts',
  path: '/Users/nik/code/skeleton/packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts'
}
file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.2.1/node_modules/extractinator/dist/cli.js:345
      throw new Error(`Unable to find dts path for "${input_path}"`);
            ^

Error: Unable to find dts path for "/Users/nik/code/skeleton/packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts"
    at emit_dts (file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.2.1/node_modules/extractinator/dist/cli.js:345:13)
    at async extractinator (file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.2.1/node_modules/extractinator/dist/cli.js:362:15)
    at async file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.2.1/node_modules/extractinator/dist/cli.js:419:27

Node.js v21.4.0
```

Is there some config I should be looking into (seems to be the same issue that came up for eulertour as well).

**Comment by braebo** [comment]
fixed in 57d1270122078b9a461496eec19507e0e75d5c37

will merge soon!

**Comment by ghostdevv** [comment]
Should be fixed in `extractinator@0.3.0` :pray:

**Comment by niktek** [comment]
Hi,

This seemed to fix things in one of the projects.  But it still failed to work on the Skeleton monorepo.

```
~/code/skeleton/packages/skeleton pnpm extractinator extract src/lib out/
Writing dts files to "/Users/nik/code/skeleton/packages/skeleton/.extractinator/dts-1703336102778"

{
  dts_path: '/Users/nik/code/skeleton/packages/skeleton/.extractinator/dts-1703336102778/actions/Clipboard/additional-svelte-typings.d.d.ts',
  input_path: '/Users/nik/code/skeleton/packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts'
}
file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:393
      throw new Error(`Unable to find dts path for "${input_path}"`);
            ^

Error: Unable to find dts path for "/Users/nik/code/skeleton/packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts"
    at emit_dts (file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:393:13)
    at async extractinator (file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:410:41)
    at async file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:486:27

Node.js v21.4.0
```

Looks like it is related to the input already being a d.ts file and it is not being present in the .extractinator folder and the d.d.ts reference ??

**Comment by ghostdevv** [comment]
Looks like a different bug, made an issue: #24 @niktek
